"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from core.helper import str_to_bool
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', default="django-insecure-lp6h18zq4@z30symy*oz)+hp^uoti48r_ix^qc-m@&yfxd7&hn")
DEV_MODE = False
DEBUG = True

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", default="localhost").split(",")

DB_NAME=os.environ.get("DB_NAME",default="")
DB_USER=os.environ.get("DB_USER",default="")
DB_PASSWORD=os.environ.get("DB_PASSWORD",default="")
DB_HOST=os.environ.get("DB_HOST",default="")
DB_PORT=os.environ.get("DB_PORT",default="")

REDIS_HOST=os.environ.get("REDIS_HOST",default="")
REDIS_LOCATION=os.environ.get("REDIS_LOCATION",default="")
REDIS_PORT=os.environ.get("REDIS_PORT",default="")
REDIS_DB=os.environ.get("REDIS_DB",default="")

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", default="")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", default=25))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = str_to_bool(os.environ.get("EMAIL_USE_TLS", default="False"))
EMAIL_USE_SSL = str_to_bool(os.environ.get("EMAIL_USE_SSL", default="False"))
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", default=10))
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "noreply@videoflix.local",
)
BACKEND_BASE_URL = os.getenv("BACKEND_BASE_URL", "http://localhost:8000")
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:5500")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_rq',
    "auth_app.apps.AuthAppConfig",
    'video_app.apps.VideoAppConfig',
    "rest_framework_simplejwt.token_blacklist",
    'drf_spectacular',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'core.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5500",
    "http://localhost:4200",   # Angular
    "http://127.0.0.1:5500",   # Live Server
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:5500",
    "http://localhost:5500",
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", default="videoflix_db"),
        "USER": os.environ.get("DB_USER", default="videoflix_user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", default="supersecretpassword"),
        "HOST": os.environ.get("DB_HOST", default="db"),
        "PORT": os.environ.get("DB_PORT", default=5432)
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_LOCATION", default="redis://redis:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "videoflix"
    }
}

RQ_QUEUES = {
    'default': {
        'HOST': 'redis',
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': 1800,
        'DEFAULT_RESULT_TTL': 800,
    }
}
# RQ_EXCEPTION_HANDLERS = ['path.to.my.handler'] 

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

 # Spectacular Settings

SPECTACULAR_SETTINGS = {
    "TITLE": "Videoflix API",
    "DESCRIPTION": "API documentation for Videoflix",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "TAGS": [

        {
            "name": "Auth",
            "description": (
                "Authentication workflow:\n\n"
                "1. Register a new user\n"
                "2. Activate account via email link\n"
                "3. Login to receive cookies\n"
                "4. Refresh access token\n"
                "5. Logout and invalidate tokens\n"
                "6. Reset password via email\n"
                "7. Confirm new password"
            ),
        },
        {
            "name": "Video",
            "description": (
                "Video streaming endpoints based on HTTP Live Streaming (HLS).\n\n"

                "Workflow:\n"
                "1. Retrieve a list of available videos\n"
                "2. Request a playlist (.m3u8) for a specific video and resolution\n"
                "3. The video player automatically loads video segments (.ts)\n\n"

                "Notes:\n"
                "- The playlist (.m3u8) contains references to video segments\n"
                "- Segment endpoints are consumed by video players and not intended for manual use\n"
                "- Supported resolutions depend on the source video (no upscaling)\n"
            ),
        },
        ],    
    "SWAGGER_UI_SETTINGS": {
        "operationsSorter": "alpha",
    },
}
