# Generated by Django 5.2.12 on 2026-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_require_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='resolutions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
